# -*- coding: utf-8 -*-
partner_codes:
  fales:       Fales Library & Special Collections
  nyuarchives: NYU Archives
  tamwag:      Tamiment Library and Robert F. Wagner Labor Archives
  abudhabi:    Abu Dhabi

filename_partner_codes:
  fa:          fales
  tw:          tamwag
  us:          nyuarchives

collection_codes:
  aia30:            "aia30 :: Ireland House Oral Histories"
  mc233:            "mc233 :: Tony Judt Papers"
  mc4:              "mc4 :: 2014 Capstones"
  mss56:	          "mss56 :: E. L. Doctorow Papers"
  mss221:           "mss221 :: Sylvere Lotringer Papers and Semiotext(e) Archive"
  mss217:           "mss217 :: Jeremy Blake Papers"
  mss270:           "mss270 :: Public Art Fund Records"
  mss279:           "mss279 :: New York Womens Culinary Alliance"
  mss326:           "mss326 :: Robert Flaherty Film Seminar Archive"
  mss350:           "mss350 :: Malcolm Goldstein Papers"   
  mss343:           "mss343 :: Exit Art Archive"
  mss384:           "mss384 :: Performance Studies International"
  mss402:           "mss402 :: I'm From Driftwood Archive"
  mss405:           "mss405 :: Larry Polansky Papers"
  mss408:           "mss408 :: Heritage Radio Network Collection"
  mss413:           "mss413 :: Maria Irene Fornes Papers"
  mss415:           "mss415 :: Fortnight Project"
  mss419:           "mss419 :: Third Streaming Archive"
  mss421:	          "mss421 :: Richard Berkowitz Papers"
  mss426:           "mss426 :: Gay USA"
  mss429:           "mss429 :: José Muñoz Papers"
  mss443:           "mss443 :: Hedi El Kholti Semiotext(e) Papers" 
  oh68:             "oh68 :: Squatters Collective Oral History Project"
  rg35-2:           "rg35-2 :: Records of the Alternative Media Center and Interactive Telecommunications Program, Tisch School of the Arts"
  rg37-49:          "rg37-49 :: NYU Humanities Inititive Records"
  rg21-46:          "rg21-46 :: ICAS"
  tam139:           "tam139  :: Greenwich House Records"
  tam261:           "tam261 :: Robert Fitch Papers"
  tam268:           "tam268 :: Sol Yurick Manuscripts for Publication"
  tam517:           "tam517 :: Philip Agee Papers"
  tam616:           "tam616 :: Estela and Ernesto Bravo Film and Video Collection"
  tam642:           "tam642 :: Dissent Magazine Records"
  tam635:           "tam635 :: Brecht Forum Records"
  tam644:	          "tam644 :: Virginia Cornue Papers"
  tam663:           "mss663 :: Pauline Park Papers"
  tam667:           "mss667 :: Donald Daughtry Papers"
  tam675:           "tam675 :: Gay Asian & Pacific Islander Men of New York Records"
  tam676:           "tam676 :: Jessie Taft Papers"
  tam677:	          "tam677 :: Carl Lichtenstein Papers"
  tam679:           "tam679 :: Marc Kagan Papers"
  tam680:           "tam680 :: Martin Popper Papers"
  vid18:            "vid18 :: Tamiment Library Video Oral Histories"
  wag328:	          "wag328 :: NYC Labor Council for Latin American Advancement Records"
  wag332:           "wag332 :: US Labor Against the War Records" 

mediatypes:
  mediatype_transfer:             "Network Transfer"
  mediatype_floppy_3_5:           "3.5 in. Floppy Disk"
  mediatype_floppy_5_25:          "5.25 in. Floppy Disk"
  mediatype_hard_disk_drive:      "Hard Disk Drive"
  mediatype_flash_drive:          "Flash Drive"
  mediatype_dvd:                  "DVD commercial"
  mediatype_dvdr:                 "DVD-R"
  mediatype_dvdrw:		            "DVD-RW"
  mediatype_cd:                   "CD commercial"
  mediatype_cdr:		              "CD-R"
  mediatype_cdrw:		              "CD-RW"
  mediatype_cdda:		              "Audio CD"
  mediatype_jaz:                  "Jaz Drive"
  mediatype_zip:		              "Zip Disk"
  mediatype_sd:                   "SD Card"

interfaces:
  interface_tableau_ultrabay:     "Tableau Ultrabay"
  interface_kryoflux:             "KryoFlux"
  interface_tableau_t8r2:	  "Tableau T8-R2"
  interface_optical_HP:		  "HP CD/DVD Drive"

imaging_software:
  imaging_software_kryoflux_imager_v220:      "KryoFlux Imager (DTC 2.20)"
  imaging_software_ftk_imager_v3146:           "FTK Imager (v3.1.4.6)"

hdd_interfaces:
  hdd_interface_usb:    "USB"
  hdd_interface_sata:   "SATA"
  hdd_interface_fw400:  "FW400"
  hdd_interface_fw800:  "FW800"
  hdd_interface_scsi:   "SCSI"

image_formats:
  image_format_raw:     "Raw"
  image_format_e01:     "E01"
  image_format_ad1:     "AD1"
  image_format_iso:     "ISO"

encoding_schemes:
  encoding_scheme_mfm:           "MFM"
  encoding_scheme_apple_400_800: "Apple 400/800"

filesystems:
  filesystem_fat12:                 "FAT12"
  filesystem_fat16:                 "FAT16"
  filesystem_fat32:                 "FAT32"
  filesystem_ntfs:                  "NTFS"
  filesystem_hfs:                   "HFS"
  filesystem_hfs_plus:              "HFS+"
  filesystem_amiga_os:              "AmigaOS"
  filesystem_9660:		              "ISO 9660"
  filesystem_9660_joliet:	          "ISO 9660 Joliet"
  filesystem_udf:		                "UDF"

image_success:
  image_sucess_yes:		"Yes"
  image_success_no:		"No"

interpret_success: 
  interpret_success_yes:	"Yes"
  interpret_success_yes_errors:	"Yes W/Errors"
  interpret_succes_no: 		"No"

stock_unit:
  KB: "Kilabytes"
  MB: "Megabytes"
  GB: "Gigabytes"
  TB: "Terabytes"

